services:
  mongo:
    image: mongo
    restart: always

    volumes:
      - ./data/mongo:/data/db

  minio:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './data/minio:/bitnami/minio/data'

    environment:
      - MINIO_ROOT_USER=grocky-minio
      - MINIO_ROOT_PASSWORD=grocky-minio
  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app

    ports:
      - 8000:8000

    env_file:
      - ./.env

    stop_signal: SIGINT
    depends_on:
      - mongo
      - minio

  client:
    restart: always
    build: ./grocky
    volumes:
      - ./grocky:/usr/src/app

    ports:
      - 5173:5173

    depends_on:
      - api