services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app

    ports:
      - 8000:8000

    env_file:
      - ./.env

    stop_signal: SIGINT

  client:
    build: ./grocky
    volumes:
      - ./grocky:/usr/src/app

    ports:
      - 5173:5173

    depends_on:
      - api